2025-06-12 02:21:33,078 INFO    MainThread:2193444 [internal.py:wandb_internal():90] W&B internal server running at pid: 2193444, started at: 2025-06-12 02:21:33.077852
2025-06-12 02:21:33,080 DEBUG   HandlerThread:2193444 [handler.py:handle_request():141] handle_request: run_start
2025-06-12 02:21:33,082 INFO    WriterThread:2193444 [datastore.py:open_for_write():75] open: /data2/xxw_data/projects/LLM/Diffusive-Latent-CoT/wandb/offline-run-20250612_022132-6wxkjo58/run-6wxkjo58.wandb
2025-06-12 02:21:33,097 DEBUG   HandlerThread:2193444 [meta.py:__init__():35] meta init
2025-06-12 02:21:33,097 DEBUG   HandlerThread:2193444 [meta.py:__init__():49] meta init done
2025-06-12 02:21:33,097 DEBUG   HandlerThread:2193444 [meta.py:probe():209] probe
2025-06-12 02:21:33,106 DEBUG   HandlerThread:2193444 [meta.py:_setup_git():199] setup git
2025-06-12 02:21:33,117 DEBUG   HandlerThread:2193444 [meta.py:_setup_git():206] setup git done
2025-06-12 02:21:33,117 DEBUG   HandlerThread:2193444 [meta.py:_save_pip():53] save pip
2025-06-12 02:21:33,118 DEBUG   HandlerThread:2193444 [meta.py:_save_pip():67] save pip done
2025-06-12 02:21:33,118 DEBUG   HandlerThread:2193444 [meta.py:_save_conda():74] save conda
2025-06-12 02:21:34,104 WARNING MainThread:2193444 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-06-12 02:21:34,164 DEBUG   HandlerThread:2193444 [meta.py:_save_conda():84] save conda done
2025-06-12 02:21:34,164 DEBUG   HandlerThread:2193444 [meta.py:probe():247] probe done
2025-06-12 02:21:34,539 WARNING MainThread:2193444 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-06-12 02:21:34,539 ERROR   MainThread:2193444 [internal.py:wandb_internal():156] Internal process interrupted.
2025-06-12 02:21:34,824 INFO    MainThread:2193444 [internal.py:handle_exit():80] Internal process exited
