2025-06-12 02:21:33,044 INFO    MainThread:2193439 [internal.py:wandb_internal():90] W&B internal server running at pid: 2193439, started at: 2025-06-12 02:21:33.044553
2025-06-12 02:21:33,047 DEBUG   HandlerThread:2193439 [handler.py:handle_request():141] handle_request: run_start
2025-06-12 02:21:33,048 INFO    WriterThread:2193439 [datastore.py:open_for_write():75] open: /data2/xxw_data/projects/LLM/Diffusive-Latent-CoT/wandb/offline-run-20250612_022132-3g1qku2w/run-3g1qku2w.wandb
2025-06-12 02:21:33,062 DEBUG   HandlerThread:2193439 [meta.py:__init__():35] meta init
2025-06-12 02:21:33,063 DEBUG   HandlerThread:2193439 [meta.py:__init__():49] meta init done
2025-06-12 02:21:33,063 DEBUG   HandlerThread:2193439 [meta.py:probe():209] probe
2025-06-12 02:21:33,071 DEBUG   HandlerThread:2193439 [meta.py:_setup_git():199] setup git
2025-06-12 02:21:33,081 DEBUG   HandlerThread:2193439 [meta.py:_setup_git():206] setup git done
2025-06-12 02:21:33,081 DEBUG   HandlerThread:2193439 [meta.py:_save_pip():53] save pip
2025-06-12 02:21:33,082 DEBUG   HandlerThread:2193439 [meta.py:_save_pip():67] save pip done
2025-06-12 02:21:33,082 DEBUG   HandlerThread:2193439 [meta.py:_save_conda():74] save conda
2025-06-12 02:21:34,104 WARNING MainThread:2193439 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-06-12 02:21:34,167 DEBUG   HandlerThread:2193439 [meta.py:_save_conda():84] save conda done
2025-06-12 02:21:34,168 DEBUG   HandlerThread:2193439 [meta.py:probe():247] probe done
2025-06-12 02:21:34,539 WARNING MainThread:2193439 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-06-12 02:21:34,539 ERROR   MainThread:2193439 [internal.py:wandb_internal():156] Internal process interrupted.
2025-06-12 02:21:34,824 INFO    MainThread:2193439 [internal.py:handle_exit():80] Internal process exited
